### ISSUE TITLE
New quickfix missing focus item state

### ISSUE THREAD

**Issue by trangcongthanh** [drcmda/poimandres-theme#12]
After update to vscode version 1.71.0, I notices that the theme missing highlight/focus state for the new quickfix action menu.

### VSCode Dark
<img width="309" alt="image" src="https://user-images.githubusercontent.com/14819342/188362021-ce5118fb-3dc6-441b-9b4f-cb619c5f47a9.png">

### Poimandres
<img width="299" alt="image" src="https://user-images.githubusercontent.com/14819342/188362114-64151783-b19e-43d5-93f8-5be986b28e83.png">

### My VSCode version:
Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (3 days ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

**Comment by brokenthorn** [comment]
This applies to the focused state in the EXPLORER. Unless the EXPLORER is actively focused by the user (i.e., interacted with), the focus state disappears once you click inside the code editor.

Also, changing the focused that only changes the focused item in the OPEN EDITORS section in the EXPLORER, but the code tree stays the same, without the currently focused tab also being focused on the EXPLORER.

And no, I haven't messed with the settings or "explorer.autoReveal" (although even that doesn't help).

**Comment by JohnVicke** [comment]
Been using this for a while and thought I would share. You can add a custom selection color of your choice by editing the `settings.json` file.

1. Open command palette
`ctrl + shift + p`

2. Search for:
 `Preferences: Open User Settings (JSON)`

3. Add color customizations override to config:
```
"workbench.colorCustomizations": {
    "menu.selectionBackground": "#404350" // hex color override 
  },
