### ISSUE TITLE
Do you have any plans to release for JetBrains IDE's?

### ISSUE THREAD

**Issue by sefatanam** [drcmda/poimandres-theme#24]
I love this theme in VS Code, but when I switched to WebStorm, I couldn't find it in their marketplace. Therefore, I would like to request support for JetBrains IDEs such as IntelliJ IDEA and PyCharm in the future. 
TIA

**Comment by marko-mihajlovic** [comment]
Hey @sefatanam 
I was in same situation as you, so I adapted the theme for JetBrains:
https://plugins.jetbrains.com/plugin/21121-poimandres-theme

Raise [an issue](https://github.com/marko-mihajlovic/poimandres-jetbrains/issues) if there is some inconsistency.

**Comment by sefatanam** [comment]
Hey @marko-mihajlovic,
Thank you for resolving this issue! Your prompt action and dedication to addressing it is greatly appreciated.
