### ISSUE TITLE
editor.rulers color looks too bright

### ISSUE THREAD

**Issue by ergenekonyigit** [drcmda/poimandres-theme#4]
Hi, thanks for great theme! editor.rulers color looks bright to me. It can be like line numbers, but this is just a feedback. 
![Screen Shot 2021-03-17 at 00 28 20](https://user-images.githubusercontent.com/7110136/111382393-fd324780-86b7-11eb-848f-e24f76a9cc3f.jpg)

And, can we override primary editor color?

**Comment by drcmda** [comment]
it's fixed. you can otherwise override everything:

```json
  "workbench.colorCustomizations": {
    "[poimandres]": {
      "editor.background": "#ff4081"
    }
  },
```

**Comment by ergenekonyigit** [comment]
thank you 🙏
