### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by z0al** [drcmda/poimandres-theme#7]
Hey 👋🏻 

Would you be interested in publishing this awesome theme to https://open-vsx.org as well? Doing so will make it available for those of us who use [onivim](https://onivim.io) or [vscodium.com](https://vscodium.com/) ..etc. 

Thanks

**Comment by drcmda** [comment]
the steps to do that seem too complex. but someone wants to do it, by all means go ahead.

**Comment by z0al** [comment]
Yeah it's a bit of work but I think most of it needs to be done once and automated. I see two main parts here. 
1. Creating a developer account + generating token
2. Setting up the repo to auto publish to open-vsx in CI

It'd be nice if you're willing to do step (1).

But if you're not interested (which is totally understandable) then I guess someone needs to fork the repo and try to keep publishing regularly. I won't personally do that as it just feels weird to publish someone else's project + it's a hassle to keep it up to date.
